print('God is Great')
print('Always do more practice')
print('Always be kind on others')
print('This is good for you')
print('This is Yellow')
print('This is Green')
print('This is Red')
print('This is Blue')
print('This is Orange')
